FROM golang:1.16 AS builder
WORKDIR /go/src/hello

RUN go mod init hello

COPY hello.go /go/src/hello

RUN go build

FROM scratch
WORKDIR /go/src/hello

COPY --from=builder /go/src/hello .

CMD [ "./hello" ]